// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview AI-powered tool to analyze guest reviews and incorporate key themes into promotional material and website copy.
 *
 * - analyzeReviews - A function that handles the review analysis process.
 * - AnalyzeReviewsInput - The input type for the analyzeReviews function.
 * - AnalyzeReviewsOutput - The return type for the analyzeReviews function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const AnalyzeReviewsInputSchema = z.object({
  reviews: z
    .string()
    .describe('A collection of guest reviews, separated by newlines.'),
});
export type AnalyzeReviewsInput = z.infer<typeof AnalyzeReviewsInputSchema>;

const AnalyzeReviewsOutputSchema = z.object({
  summary: z
    .string()
    .describe(
      'A summary of the key themes and sentiments expressed in the reviews.'
    ),
  suggestedContent: z
    .string()
    .describe(
      'Suggested content incorporating the key themes, for use in promotional material and website copy.'
    ),
});
export type AnalyzeReviewsOutput = z.infer<typeof AnalyzeReviewsOutputSchema>;

export async function analyzeReviews(input: AnalyzeReviewsInput): Promise<AnalyzeReviewsOutput> {
  return analyzeReviewsFlow(input);
}

const analyzeReviewsPrompt = ai.definePrompt({
  name: 'analyzeReviewsPrompt',
  input: {schema: AnalyzeReviewsInputSchema},
  output: {schema: AnalyzeReviewsOutputSchema},
  prompt: `You are an AI assistant tasked with analyzing guest reviews for a cottage rental property.

You will be given a collection of reviews. Your goal is to identify the key themes and sentiments expressed in these reviews, and then suggest content that incorporates these themes for use in promotional material and website copy.

Reviews:
{{{reviews}}}

Summary of key themes and sentiments:

Suggested content incorporating key themes:
`,
});

const analyzeReviewsFlow = ai.defineFlow(
  {
    name: 'analyzeReviewsFlow',
    inputSchema: AnalyzeReviewsInputSchema,
    outputSchema: AnalyzeReviewsOutputSchema,
  },
  async input => {
    const {output} = await analyzeReviewsPrompt(input);
    return output!;
  }
);
